### ISSUE TITLE
Error parsing Android KeyDescription

### ISSUE THREAD

**Issue by or390** [PeculiarVentures/asn1-schema#98]
I've encountered an issue while trying to parse a certificate chain from a Motorola Edge (2022), it fails with the following error:

```
Error: Data does not match to AuthorizationList ASN1 schema. undefined
    at Function.fromASN (/dev/demo-server/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:43:23)
    at Function.fromASN (/dev/demo-server/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:126:41)
    at Function.parse (/dev/demo-server/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at extract (/dev/demo-server/test/android/test_cert_chain.js:57:26)
```

I tried to parse the same certificate with [Google's Java parser](https://github.com/google/android-key-attestation/tree/master/server/src/main/java/com/google/android/attestation) and it does parse it properly...

Replication code (includes both a certificate chain that does work and one that does not):

```js
const {AsnParser} = require('@peculiar/asn1-schema');
const {Certificate} = require("@peculiar/asn1-x509");
const {id_ce_keyDescription, KeyDescription} = require('@peculiar/asn1-android');
const assert = require('node:assert/strict');

const motorola_edge_plus = [
    '-----BEGIN CERTIFICATE-----\n' +
        'MIIDCjCCArGgAwIBAgIBATAKBggqhkjOPQQDAjA5MQwwCgYDVQQMDANURUUxKTAnBgNVBAUTIGY2\n' +
        'MGYwNmY0NjNlZmFmYWUxYTUyNDcwNDJkNjU4ZTdhMB4XDTcwMDEwMTAwMDAwMFoXDTQ4MDEwMTAw\n' +
        'MDAwMFowHzEdMBsGA1UEAwwUQW5kcm9pZCBLZXlzdG9yZSBLZXkwWTATBgcqhkjOPQIBBggqhkjO\n' +
        'PQMBBwNCAARHU+VOV5i/3yvwsv3BHQQwZASb7rt+yQ9a/JmDAyQ9EcRsxQIij4+1Q4dKEiyZNFeq\n' +
        '6fpEg9QMc94U/vS4dX4Ho4IBwjCCAb4wDgYDVR0PAQH/BAQDAgeAMIIBqgYKKwYBBAHWeQIBEQSC\n' +
        'AZowggGWAgFkCgEBAgFkCgEBBCBlY2Y3NDdhMGUwNWEwMjVlYzlkZmJjYWIyNWYyYzRiNQQAMGO/\n' +
        'hT0IAgYBiyKgHTO/hUVTBFEwTzEpMCcEIWNvbS50aWNrcGlja2xsYy5jZW9icmllbi50aWNrcGlj\n' +
        'awICASkxIgQgzgFoUbcE2nb97d40qzFKFVylpdsxJm0mhfy/KBq1ECgwgf6hCDEGAgECAgEDogMC\n' +
        'AQOjBAICAQClBTEDAgEEqgMCAQG/g3cCBQC/hT4DAgEAv4VATDBKBCDCIkVxyc1ciSAKcxGx43qp\n' +
        'z3UeLhl1Po03ArygC+HULAEB/woBAAQgY920oYE0oEfHNk1uzzc4Lmsvmqr0UZvdM10G6mWdiZO/\n' +
        'hUEFAgMB+9C/hUIFAgMDFkS/hUYKBAhtb3Rvcm9sYb+FRwcEBWhpcGhpv4VICgQIaGlwaGlfZ3a/\n' +
        'hUwKBAhtb3Rvcm9sYb+FTSEEH21vdG9yb2xhIGVkZ2UgcGx1cyA1RyBVVyAoMjAyMim/hU4GAgQB\n' +
        'NLKRv4VPBgIEATSykTAKBggqhkjOPQQDAgNHADBEAiBzmoyRYaOGl7VbICpzze/3nziH2l4MMrNM\n' +
        'PSBAyqWyGwIgNTEY467ALlbb/FB0TBJFEc72kFFVRYDdynpUFas4c08=\n' +
        '-----END CERTIFICATE-----'
]

const motorola_edge_2022 = [
    '-----BEGIN CERTIFICATE-----\n' +
        'MIIC+DCCAp6gAwIBAgIBATAKBggqhkjOPQQDAjA5MQwwCgYDVQQMDANURUUxKTAnBgNVBAUTIDZl\n' +
        'Nzg5YTcwM2YzNzkzNmQyOTNmNjgwOTBlOGMyZjBiMB4XDTcwMDEwMTAwMDAwMFoXDTQ4MDEwMTAw\n' +
        'MDAwMFowHzEdMBsGA1UEAxMUQW5kcm9pZCBLZXlzdG9yZSBLZXkwWTATBgcqhkjOPQIBBggqhkjO\n' +
        'PQMBBwNCAAS8ItMHnsni6qHvknh2xYmZmlubSmp17yj9E+kgvXhUgy/JJ2t5tUv64ofC75SVNs+c\n' +
        'WxNEgQ1AuT/ZgnkDvJAzo4IBrzCCAaswDwYDVR0PAQH/BAUDAweAADCCAZYGCisGAQQB1nkCAREE\n' +
        'ggGGMIIBggIBZAoBAQIBZAoBAQQgMWIxYWRhMzVhYzQyNmViMWY4NDVjODdlZTI5ZjBlYzMEADBX\n' +
        'v4VFUwRRME8xKTAnBCFjb20udGlja3BpY2tsbGMuY2VvYnJpZW4udGlja3BpY2sCAgEpMSIEIM4B\n' +
        'aFG3BNp2/e3eNKsxShVcpaXbMSZtJoX8vygatRAoMIH2oQgxBgIBAwIBAqIDAgEDowQCAgEApQUx\n' +
        'AwIBBKoDAgEBv4N3AgUAv4U+AwIBAL+FQEwwSgQgn7UvCVRhPyIa9PQHDDFBXtRMGoHVGInbCUZj\n' +
        'JZmz6UYBAf8KAQAEIP+u7DR3gk3YLgm2QAYC3LJ0606J3LYJOtH27elk7XPDv4VBBQIDAdTAv4VC\n' +
        'BQIDAxZEv4VNFgQUbW90b3JvbGEgZWRnZSAoMjAyMim/hUwKBAhtb3Rvcm9sYb+FSA0EC3Rlc2xh\n' +
        'X2dfc3lzv4VHBwQFdGVzbGG/hUYKBAhtb3Rvcm9sYb+FTgYCBAE0spG/hU8GAgQBNLKRMAoGCCqG\n' +
        'SM49BAMCA0gAMEUCIAMIhxYWeIxIZ2Nl11wsRteR37XZpln73vbgnME6lo8vAiEA4JhU+I7tFKSz\n' +
        '865PhKHzpJgDLMSpyEAzyCXQrTMmR6s=\n' +
        '-----END CERTIFICATE-----'
];

function fromPEM(pem) {
    const base64 = pem
        .replace(/-{5}(BEGIN|END) .*-{5}/gm, '')
        .replace(/\s/gm, '');
    return new Uint8Array(Buffer.from(base64, 'base64')).buffer;
}

function extract(certChain) {
    try {
        const cert = AsnParser.parse(fromPEM(certChain[0]), Certificate)
        const extKeyStore = cert?.tbsCertificate
            ?.extensions
            ?.find(ext => ext.extnID === id_ce_keyDescription);
        return AsnParser.parse(extKeyStore.extnValue, KeyDescription);
    } catch (e) {
        console.log(`Error extracting attestation data: ${e}`);
    }
    return undefined;
}

describe('demonstrate attestation data extraction failure', () => {
    it('certificate chain that does work', () => {
        const attestationData = extract(motorola_edge_plus);
        assert(attestationData !== undefined)
    });

    it('certificate chain that does not work', () => {
        const attestationData = extract(motorola_edge_2022);
        assert(attestationData !== undefined)
    });
});
```

**Comment by or390** [comment]
@MasterKale @rmhrisk since you were both involved in the definition of the scheme I was hoping you might have a quick insight

**Comment by microshine** [comment]
Upon comparing the ASN.1 structure you've provided with the official schema from [Android's Key Attestation Schema](https://source.android.com/security/keystore/attestation#schema), it's clear that the fields in the `AuthorizationList` must adhere to a strict sequence, which isn't the case in the provided structure.

In the ASN.1 structure (see [ASN.1](https://lapo.it/asn1js/#MIIBggIBZAoBAQIBZAoBAQQgMWIxYWRhMzVhYzQyNmViMWY4NDVjODdlZTI5ZjBlYzMEADBXv4VFUwRRME8xKTAnBCFjb20udGlja3BpY2tsbGMuY2VvYnJpZW4udGlja3BpY2sCAgEpMSIEIM4BaFG3BNp2_e3eNKsxShVcpaXbMSZtJoX8vygatRAoMIH2oQgxBgIBAwIBAqIDAgEDowQCAgEApQUxAwIBBKoDAgEBv4N3AgUAv4U-AwIBAL-FQEwwSgQgn7UvCVRhPyIa9PQHDDFBXtRMGoHVGInbCUZjJZmz6UYBAf8KAQAEIP-u7DR3gk3YLgm2QAYC3LJ0606J3LYJOtH27elk7XPDv4VBBQIDAdTAv4VCBQIDAxZEv4VNFgQUbW90b3JvbGEgZWRnZSAoMjAyMim_hUwKBAhtb3Rvcm9sYb-FSA0EC3Rlc2xhX2dfc3lzv4VHBwQFdGVzbGG_hUYKBAhtb3Rvcm9sYb-FTgYCBAE0spG_hU8GAgQBNLKR)):
```
...
[717] (1 elem)
[716] (1 elem)
[712] (1 elem)
[711] (1 elem)
[710] (1 elem)
...
```

ASN.1 schema:

```asn1
AuthorizationList ::= SEQUENCE {
  purpose                     [1] EXPLICIT SET OF INTEGER OPTIONAL,
  algorithm                   [2] EXPLICIT INTEGER OPTIONAL,
  keySize                     [3] EXPLICIT INTEGER OPTIONAL.
  digest                      [5] EXPLICIT SET OF INTEGER OPTIONAL,
  padding                     [6] EXPLICIT SET OF INTEGER OPTIONAL,
  ecCurve                     [10] EXPLICIT INTEGER OPTIONAL,
  rsaPublicExponent           [200] EXPLICIT INTEGER OPTIONAL,
  rollbackResistance          [303] EXPLICIT NULL OPTIONAL, # KM4
  activeDateTime              [400] EXPLICIT INTEGER OPTIONAL
  originationExpireDateTime   [401] EXPLICIT INTEGER OPTIONAL
  usageExpireDateTime         [402] EXPLICIT INTEGER OPTIONAL
  noAuthRequired              [503] EXPLICIT NULL OPTIONAL,
  userAuthType                [504] EXPLICIT INTEGER OPTIONAL,
  authTimeout                 [505] EXPLICIT INTEGER OPTIONAL,
  allowWhileOnBody            [506] EXPLICIT NULL OPTIONAL,
  trustedUserPresenceRequired [507] EXPLICIT NULL OPTIONAL, # KM4
  trustedConfirmationRequired [508] EXPLICIT NULL OPTIONAL, # KM4
  unlockedDeviceRequired      [509] EXPLICIT NULL OPTIONAL, # KM4
  allApplications             [600] EXPLICIT NULL OPTIONAL,
  applicationId               [601] EXPLICIT OCTET_STRING OPTIONAL,
  creationDateTime            [701] EXPLICIT INTEGER OPTIONAL,
  origin                      [702] EXPLICIT INTEGER OPTIONAL,
  rollbackResistant           [703] EXPLICIT NULL OPTIONAL, # KM2 and KM3 only.
  rootOfTrust                 [704] EXPLICIT RootOfTrust OPTIONAL,
  osVersion                   [705] EXPLICIT INTEGER OPTIONAL,
  osPatchLevel                [706] EXPLICIT INTEGER OPTIONAL,
  attestationApplicationId    [709] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdBrand          [710] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdDevice         [711] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdProduct        [712] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdSerial         [713] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdImei           [714] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdMeid           [715] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdManufacturer   [716] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  attestationIdModel          [717] EXPLICIT OCTET_STRING OPTIONAL, # KM3
  vendorPatchLevel            [718] EXPLICIT INTEGER OPTIONAL, # KM4
  bootPatchLevel              [719] EXPLICIT INTEGER OPTIONAL, # KM4
}
```

According to the Android's Key Attestation Schema, these fields should be in the sequential order `[710]`, `[711]`, `[712]`, `[716]`, `[717]`.

Thus, the primary discrepancy lies in the incorrect order of fields within the `AuthorizationList`. Implementations must ensure they adhere strictly to the defined order in the schema for proper validation and interpretation of the attestation data.

**Comment by microshine** [comment]
Here is a proposal of the schema changing  that allows for flexibility in the order of fields within the `AuthorizationList`, one approach is to use a sequence of choices. However, it's essential to note that this deviation from the standard might affect interoperability and could introduce compatibility challenges with systems expecting the strict order.

Here's an ASN.1 schema with the suggested changes:

```
AuthorizationList ::= SEQUENCE OF Authorization

Authorization ::= CHOICE {
    purpose                 [1] EXPLICIT SET OF INTEGER OPTIONAL,
    algorithm               [2] EXPLICIT INTEGER OPTIONAL,
    keySize                 [3] EXPLICIT INTEGER OPTIONAL,
    digest                  [5] EXPLICIT SET OF INTEGER OPTIONAL,
    padding                 [6] EXPLICIT SET OF INTEGER OPTIONAL,
    ...,
    origin                  [702] EXPLICIT INTEGER OPTIONAL,
    osVersion               [705] EXPLICIT INTEGER OPTIONAL,
    osPatchLevel            [706] EXPLICIT INTEGER OPTIONAL,
    ...
    attestationIdImei       [714] EXPLICIT OCTET_STRING OPTIONAL,
    attestationIdMeid       [715] EXPLICIT OCTET_STRING OPTIONAL,
    attestationIdManufacturer [716] EXPLICIT OCTET_STRING OPTIONAL,
    ...
    -- More fields as required
}
```

This schema allows for any order of `Authorization` fields within the `AuthorizationList`. However, care must be taken when interpreting the results since the field order is not guaranteed. This approach might be more forgiving in terms of parsing, but it also requires more diligence in interpreting and validating the results.

**Comment by or390** [comment]
@microshine thank you for the quick reply! I understand that the implementation must adhere to the defined order, it makes sense, but it's up to the device manufacturer. And most do, it's really an edge case I found after attesting thousands of devices, but it's interesting that Google's own parser gives no importance to the order, given it's able to parse it correctly. Is there anything we can do here to ignore the order they come in? Because the device itself is legit and passes hardware attestation and I wouldn't want to fail the attestation only because of faulty implementation by the manufacturer.

**Comment by microshine** [comment]
I believe it's possible to introduce an additional declaration in our schema to cater to such scenarios. This would allow the creation of ASN.1 structures that adhere to the specification with a strict order, while also enabling applications to read structures that have a more flexible field order.

@rmsk, what are your thoughts on this?

**Comment by microshine** [comment]
@or390 is it ok that `attestationVersion`  is 100 in your example? Because the spec requires only 3 values 

```asn
KeyDescription ::= SEQUENCE {
  attestationVersion         INTEGER, # KM2 value is 1. KM3 value is 2. KM4 value is 3.
  ...
```

ASN.1 data from your certificates

```asn
SEQUENCE (8 elem)
  INTEGER 100
  ...
```

**Comment by or390** [comment]
@microshine yes it is ok, your scheme is just a bit outdated, if you want to update it on the way that would be great :) there were some properties that were added in the new versions: https://developer.android.com/privacy-and-security/security-key-attestation#key_attestation_ext_schema

**Comment by rmhrisk** [comment]
It doesn't surprise me, unfortunately, that there are poorly crafted ASN.1 blobs out there, I am also not against having a way to enable support for them in this library. With that said I am a believer that [Postel was wrong](https://datatracker.ietf.org/doc/html/draft-thomson-postel-was-wrong-03) and being too permissive is bad.

I am also a pragmatist though and appreciate that we need to build software that works with what is out there. For example [zcrypto](https://github.com/zmap/zcrypto) exists because Censys needed to be able to understand what was out there, it was made to be super permissive as a result - This is also why it is labeled as dangerous and should never be used for a relying party application.

The questions become:
1. How do we expose this as opt-in behavior that is labeled appropriately so people do not accidentally expose themselves to potential negative side effects?
2. This will not be the only case of bad ASN.1 out there how do we do this in a way that accommodates other encoding issues in the future? Do we handle each case as one by one or do we have one meta flag that turns on this potentially unsafe behavior?

As for the schema update, looks like we should do the update.

**Comment by rmhrisk** [comment]
@or390 it looks like this new schema version adds a required field into the sequence. Normally when a new version of a schema modifies an older one it is versioned. There does not appear to be a version here though. Do we know if this version information is available to the caller higher in the stack? I really hate the idea of just trying all combinations to get to the truth.

**Comment by microshine** [comment]
Here is the difference between v2 and v3. As you can see, version 3 adds the required field `verifiedBootHash`.

```diff
RootOfTrust ::= SEQUENCE {
    verifiedBootKey  OCTET_STRING,
    deviceLocked  BOOLEAN,
    verifiedBootState  VerifiedBootState,
+   verifiedBootHash OCTET_STRING,
}
```

**Comment by or390** [comment]
@microshine I see, but it’s [already supported today ](https://github.com/PeculiarVentures/asn1-schema/blame/master/packages/android/src/key_description.ts#L46), you had to keep it optional I assume so it won’t break previous versions. As far as I know, the only trustworthy way to know the attestation version and match a specific schema to it (that is if you don’t want to keep one fit all that is too permissive) is to read it from the KeyDescription.

**Comment by microshine** [comment]
I wanted to let you know that we've released `@peculiar/asn1-android@2.3.8`. In this update, we've added the `NonStandardKeyDescription` class to address those extensions with out-of-order fields. Plus, the `AttestationApplicationId` schema is now in place.

You can check out some usage examples in our [GitHub README](https://github.com/PeculiarVentures/asn1-schema/blob/ef4e3ee41b32a2ab938b70118c66d6f8388906e8/packages/android/README.md#keydescription-and-nonstandardkeydescription).

Would appreciate your feedback if you have the time to test this new release.

**Comment by or390** [comment]
@microshine thanks again for the quick support! I'll test this version over the weekend and get back to you early next week.

few minor comments

I suggest changing the field names of Version enum as follows. And since the values of AttestationVersion and KeymasterVersion means two different things, I also think it's better to rename it to AttestationVersion to avoid confusion. Or you could maybe get rid of it all together, as the property itself is an integer anyway and not an enum, and it will get outdated quickly (there is already attestation version 300 that is yet to be documented by Google).

export declare enum AttestationVersion {
    keymaster2 = 1,
    keymaster3 = 2,
    keymaster4 = 3,
    keymaster4_1 = 4,
    keyMint1 = 100,
    keyMint2= 200
}

The comment above VerifiedBootState mistakenly says it's a structure for attestation package info.

Lastly, does it really make sense to set default values in KeyDescription? [e.g attestation version 4](https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/android/src/key_description.ts#L298), if it's a required field I would except the attestation to fail if it's missing, and if that is the case, why do we need default value at all?

**Comment by microshine** [comment]
I've rolled out a new build `@peculiar/asn1-android@2.3.9` that encompasses the following updates:

1. Fixed documentation pertaining to `VerifiedBootState`.
2. Enhanced `attestationVersion` to now support both `enum` and `number` types.
3. Updated the values for the `Version` enum:

**Previous:**
```typescript
export enum Version {
  KM2 = 1,
  KM3 = 2,
  KM4 = 3,
  v4 = 4,
  v100 = 100,
  v200 = 200,
}
```

**Current:**
```typescript
export enum Version {
  KM2 = 1,
  KM3 = 2,
  KM4 = 3,
  KM4_1 = 4,
  keyMint1 = 100,
  keyMint2 = 200,
}
```

On a side note, I've contemplated the idea of renaming `Version` to `AttestationVersion`. However, given that this module is a dependency for several projects, such a change would lead to a major version bump. For the sake of version compatibility, I believe it's prudent to retain the name `Version`.

**Comment by or390** [comment]
@microshine makes sense, thanks! p.s. noticed two fields are still missing in the schema: mgfDigest and usageCountLimit

**Comment by donskov** [comment]
Hey @or390. Added support Android extension to the [certificates viewer](https://understandingwebpki.com/?cert=MIIC%2BDCCAp6gAwIBAgIBATAKBggqhkjOPQQDAjA5MQwwCgYDVQQMDANURUUxKTAnBgNVBAUTIDZlNzg5YTcwM2YzNzkzNmQyOTNmNjgwOTBlOGMyZjBiMB4XDTcwMDEwMTAwMDAwMFoXDTQ4MDEwMTAwMDAwMFowHzEdMBsGA1UEAxMUQW5kcm9pZCBLZXlzdG9yZSBLZXkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS8ItMHnsni6qHvknh2xYmZmlubSmp17yj9E%2BkgvXhUgy%2FJJ2t5tUv64ofC75SVNs%2BcWxNEgQ1AuT%2FZgnkDvJAzo4IBrzCCAaswDwYDVR0PAQH%2FBAUDAweAADCCAZYGCisGAQQB1nkCAREEggGGMIIBggIBZAoBAQIBZAoBAQQgMWIxYWRhMzVhYzQyNmViMWY4NDVjODdlZTI5ZjBlYzMEADBXv4VFUwRRME8xKTAnBCFjb20udGlja3BpY2tsbGMuY2VvYnJpZW4udGlja3BpY2sCAgEpMSIEIM4BaFG3BNp2%2Fe3eNKsxShVcpaXbMSZtJoX8vygatRAoMIH2oQgxBgIBAwIBAqIDAgEDowQCAgEApQUxAwIBBKoDAgEBv4N3AgUAv4U%2BAwIBAL%2BFQEwwSgQgn7UvCVRhPyIa9PQHDDFBXtRMGoHVGInbCUZjJZmz6UYBAf8KAQAEIP%2Bu7DR3gk3YLgm2QAYC3LJ0606J3LYJOtH27elk7XPDv4VBBQIDAdTAv4VCBQIDAxZEv4VNFgQUbW90b3JvbGEgZWRnZSAoMjAyMim%2FhUwKBAhtb3Rvcm9sYb%2BFSA0EC3Rlc2xhX2dfc3lzv4VHBwQFdGVzbGG%2FhUYKBAhtb3Rvcm9sYb%2BFTgYCBAE0spG%2FhU8GAgQBNLKRMAoGCCqGSM49BAMCA0gAMEUCIAMIhxYWeIxIZ2Nl11wsRteR37XZpln73vbgnME6lo8vAiEA4JhU%2BI7tFKSz865PhKHzpJgDLMSpyEAzyCXQrTMmR6s%3D). Maybe it will help to quickly check the information.

**Comment by or390** [comment]
@microshine Some numbers from the weekend: after parsing 34K certificate chains, only 649 failed to parse using KeyDescription, but all worked with the new NonStandardKeyDescription.

**Comment by microshine** [comment]
@or390 I've published `@peculiar/asn1-android@2.3.10`. It supports missed fields `mgfDigest` and `usageCountLimit`
